Repository zen-mod/GME_AR, pull requests merged in 2022-06, with the labels that each got.

#2 Fix delete all dead in MP
  Configs/Editor/ActionLists/Context/Shared.conf
Labels: bug fix

#3 Fixes drawing preview lines to already completed waypoints
  README.md
  Scripts/Game/Editor/Components/EditableEntity/Modded/SCR_EditableGroupComponent.c
  Scripts/Game/Editor/Components/EditableEntity/Modded/SCR_EditableWaypointComponent.c
  Scripts/Game/Editor/UI/Components/EditableEntityFilters/Modded/SCR_WaypointLinesEditorUIComponent.c
Labels: bug fix

#9 Move stance to character attribute group
  Configs/Editor/AttributeLists/Edit.conf
  Scripts/Game/Editor/Containers/Attributes/ODIN_StanceEditorAttribute.c
Labels: enhancement

#8 Add waypoint attributes
  Configs/Editor/AttributeCategories/Waypoint.conf
  Configs/Editor/AttributeCategories/Waypoint.conf.meta
  Configs/Editor/AttributeLists/Edit.conf
  Language/localization.st
  PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Defend.et
  PrefabsEditable/Auto/AI/Waypoints/E_AIWaypoint_Defend.et.meta
  README.md
  Scripts/Game/Editor/Containers/Attributes/ODIN_CompletionRadiusEditorAttribute.c
  Scripts/Game/Editor/Containers/Attributes/ODIN_CompletionTypeEditorAttribute.c
Labels: feature
