Repository zen-mod/GME_AR, pull requests merged in 2024-10, with the labels that each got.

#6 Add placeable intel with editable text
  addons/GME/Configs/Editor/AttributeCategories/Intel.conf
  addons/GME/Configs/Editor/AttributeCategories/Intel.conf.meta
  addons/GME/Configs/Editor/AttributeLists/Edit.conf
  addons/GME/Configs/Editor/PlaceableEntities/Systems/Systems.conf
  addons/GME/Configs/Editor/PlaceableEntities/Systems/Systems.conf.meta
  addons/GME/Configs/Notifications/Notifications.conf
  addons/GME/Language/GME_localization.cs_cz.conf
  addons/GME/Language/GME_localization.de_de.conf
  addons/GME/Language/GME_localization.en_us.conf
  addons/GME/Language/GME_localization.es_es.conf
  addons/GME/Language/GME_localization.fr_fr.conf
  addons/GME/Language/GME_localization.it_it.conf
  addons/GME/Language/GME_localization.ja_jp.conf
  addons/GME/Language/GME_localization.ko_kr.conf
  addons/GME/Language/GME_localization.pl_pl.conf
  addons/GME/Language/GME_localization.pt_br.conf
  addons/GME/Language/GME_localization.ru_ru.conf
  addons/GME/Language/GME_localization.st
  addons/GME/Language/GME_localization.uk_ua.conf
  addons/GME/Language/GME_localization.zh_cn.conf
  addons/GME/Prefabs/Items/Misc/IntelligenceFolder_E_01/E_GME_IntelFolder_01.et
  addons/GME/Prefabs/Items/Misc/IntelligenceFolder_E_01/E_GME_IntelFolder_01.et.meta
  addons/GME/Scripts/Game/GME/Components/Intel/GME_IntelComponent.c
  addons/GME/Scripts/Game/GME/Editor/Containers/AttributeVariables/SCR_BaseEditorAttributeVar.c
  addons/GME/Scripts/Game/GME/Editor/Containers/Attributes/ODIN_IntelContentEditorAttribute.c
  addons/GME/Scripts/Game/GME/Editor/Containers/Attributes/ODIN_IntelTitleEditorAttribute.c
  addons/GME/Scripts/Game/GME/Network/Notifications/ENotification.c
  addons/GME/Scripts/Game/GME/UI/Components/Attributes/GME_EditBoxEditorAttributeUIComponent.c
  addons/GME/Scripts/Game/GME/UI/Components/Attributes/GME_MultilineEditBoxEditorAttributeUIComponent.c
  addons/GME/Scripts/Game/GME/UI/Components/WidgetLibrary/SCR_EditBox/GME_MultilineEditBoxComponent.c
  addons/GME/UI/Textures/EditorPreviews/Auto/Systems/Intel/IntelligenceFolder_E_01.edds
  addons/GME/UI/Textures/EditorPreviews/Auto/Systems/Intel/IntelligenceFolder_E_01.edds.meta
  addons/GME/UI/Textures/EditorPreviews/Auto/Systems/Intel/IntelligenceFolder_E_01.png
  addons/GME/UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Edit.layout.meta
  addons/GME/UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_EditBox.layout
  addons/GME/UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_EditBox.layout.meta
  addons/GME/UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_MultilineEditBox.layout
  addons/GME/UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_MultilineEditBox.layout.meta
  addons/GME/UI/layouts/WidgetLibrary/EditBox/WLib_MultilineEditBox.layout
  addons/GME/UI/layouts/WidgetLibrary/EditBox/WLib_MultilineEditBox.layout.meta
Labels: feature

#52 Revise module framework
  addons/GME/Scripts/Game/GME/Components/EditableEntity/GME_Modules_EditableModuleComponent.c
  addons/GME/Scripts/Game/GME/Editor/Modules/GME_Modules_Base.c
  addons/GME/Scripts/Game/GME/Editor/Modules/InitActions/GME_Modules_InitAction_Base.c
  addons/GME/Scripts/Game/GME/Editor/Modules/InitActions/GME_Modules_InitAction_ChoosePassengers.c
  addons/GME/Scripts/Game/GME/Editor/Modules/InitActions/GME_Modules_InitAction_EditAttributes.c
  addons/GME/Scripts/Game/GME/Editor/Modules/InitActions/GME_Modules_InitAction_EditorBrowserBase.c
  addons/GME/Scripts/Game/GME/Editor/Modules/InitActions/GME_Modules_InitAction_ExtendEntity.c
  addons/GME/Scripts/Game/GME/Editor/Modules/InitActions/GME_Modules_InitAction_PlaceEntity.c
  addons/GME/Scripts/Game/GME/Editor/Modules/InitActions/GME_Modules_InitAction_RequireEntityInWorld.c
  addons/GME/Scripts/Game/GME/Editor/Modules/InitActions/GME_Modules_InitAction_Sleep.c
  addons/GME/Scripts/Game/GME/Editor/Modules/InitActions/GME_Modules_InitAction_SpawnDefaultOccupants.c
  addons/GME/Scripts/Game/GME/Entities/SCR_AIGroup.c
  addons/GME/Scripts/Game/GME/Helpers/GME_EditableEntityHelper.c
  addons/GME/Scripts/Game/GME/Helpers/GME_GroupHelper.c
  addons/GME/Scripts/Game/GME/Helpers/GME_VehicleHelper.c
Labels: refactor

#7 Enhance skill attribute
  addons/GME/Configs/Editor/AttributeLists/Edit.conf
  addons/GME/Language/GME_localization.cs_cz.conf
  addons/GME/Language/GME_localization.de_de.conf
  addons/GME/Language/GME_localization.en_us.conf
  addons/GME/Language/GME_localization.es_es.conf
  addons/GME/Language/GME_localization.fr_fr.conf
  addons/GME/Language/GME_localization.it_it.conf
  addons/GME/Language/GME_localization.ja_jp.conf
  addons/GME/Language/GME_localization.ko_kr.conf
  addons/GME/Language/GME_localization.pl_pl.conf
  addons/GME/Language/GME_localization.pt_br.conf
  addons/GME/Language/GME_localization.ru_ru.conf
  addons/GME/Language/GME_localization.st
  addons/GME/Language/GME_localization.uk_ua.conf
  addons/GME/Language/GME_localization.zh_cn.conf
  addons/GME/Scripts/Game/GME/Editor/Containers/Attributes/GME_AISkillEditorAttribute.c
  addons/GME/Scripts/Game/GME/Editor/Containers/Attributes/GME_BaseAISkillEditorAttribute.c
  addons/GME/Scripts/Game/GME/Editor/Containers/Attributes/GME_GlobalAISkillEditorAttribute.c
  addons/GME/Scripts/Game/GME/Editor/Containers/Attributes/GME_SkillEditorAttribute.c
  addons/GME/Scripts/Game/GME/GameMode/SCR_BaseGameMode.c
  addons/GME/Scripts/Game/GME/Mission/SCR_MissionHeader.c
  addons/GME/Scripts/GameCode/GME/Character/SCR_ChimeraCharacter.c
Labels: feature

#49 Add ambient flyby modules
  addons/GME/Configs/Core/EditableEntityCore.conf
  addons/GME/Configs/Editor/AttributeLists/Edit.conf
  addons/GME/Configs/Editor/AttributeLists/GME_Modules.conf
  addons/GME/Configs/Editor/PlaceableEntities/Systems/Systems.conf
  addons/GME/Configs/Notifications/Notifications.conf
  addons/GME/Language/GME_localization.cs_cz.conf
  addons/GME/Language/GME_localization.de_de.conf
  addons/GME/Language/GME_localization.en_us.conf
  addons/GME/Language/GME_localization.es_es.conf
  addons/GME/Language/GME_localization.fr_fr.conf
  addons/GME/Language/GME_localization.it_it.conf
  addons/GME/Language/GME_localization.ja_jp.conf
  addons/GME/Language/GME_localization.ko_kr.conf
  addons/GME/Language/GME_localization.pl_pl.conf
  addons/GME/Language/GME_localization.pt_br.conf
  addons/GME/Language/GME_localization.ru_ru.conf
  addons/GME/Language/GME_localization.st
  addons/GME/Language/GME_localization.uk_ua.conf
  addons/GME/Language/GME_localization.zh_cn.conf
  addons/GME/Prefabs/Vehicles/Helicopters/Mi8MT/GME_Mi8MT_ambient.et
  addons/GME/Prefabs/Vehicles/Helicopters/Mi8MT/GME_Mi8MT_ambient.et.meta
  addons/GME/Prefabs/Vehicles/Helicopters/UH1H/GME_UH1H_ambient.et
  addons/GME/Prefabs/Vehicles/Helicopters/UH1H/GME_UH1H_ambient.et.meta
  addons/GME/PrefabsEditable/Modules/AI/E_GME_Modules_AmbientFlybyBase.et
  addons/GME/PrefabsEditable/Modules/AI/E_GME_Modules_AmbientFlybyBase.et.meta
  addons/GME/PrefabsEditable/Modules/AI/E_GME_Modules_AmbientMi8MTFlyby.et
  addons/GME/PrefabsEditable/Modules/AI/E_GME_Modules_AmbientMi8MTFlyby.et.meta
  addons/GME/PrefabsEditable/Modules/AI/E_GME_Modules_AmbientUH1HFlyby.et
  addons/GME/PrefabsEditable/Modules/AI/E_GME_Modules_AmbientUH1HFlyby.et.meta
  addons/GME/Scripts/Game/GME/Components/GME_AmbientFlybyComponent.c
  addons/GME/Scripts/Game/GME/Editor/Containers/Attributes/Modules/GME_Modules_Attribute_FlybyHeight.c
  addons/GME/Scripts/Game/GME/Editor/Containers/Attributes/Modules/GME_Modules_Attribute_FlybySpeed.c
  addons/GME/Scripts/Game/GME/Editor/Containers/Attributes/Modules/GME_Modules_Attribute_FlybyStartDistance.c
  addons/GME/Scripts/Game/GME/Editor/Enums/EEditableEntityLabel.c
  addons/GME/Scripts/Game/GME/Editor/Modules/GME_Modules_AmbientFlyby.c
Labels: feature

#57 Fix script error when loading skill attributes from a save
  addons/GME/Scripts/Game/GME/Editor/Containers/Attributes/GME_BaseAISkillEditorAttribute.c
Labels: bug fix, ignore changelog

#56 Fix inconsistent usage of "recursively" option for visibility flags
  addons/GME/Scripts/Game/GME/Helpers/GME_VisibilityHelper.c
  addons/GME/Scripts/GameCode/GME/Character/SCR_ChimeraCharacter.c
  addons/GME/Scripts/GameCode/GME/Vehicle/Vehicle.c
Labels: bug fix

#58 Fix typo in intel title
  addons/GME/Language/GME_localization.cs_cz.conf
  addons/GME/Language/GME_localization.en_us.conf
  addons/GME/Language/GME_localization.es_es.conf
  addons/GME/Language/GME_localization.fr_fr.conf
  addons/GME/Language/GME_localization.it_it.conf
  addons/GME/Language/GME_localization.ja_jp.conf
  addons/GME/Language/GME_localization.ko_kr.conf
  addons/GME/Language/GME_localization.pl_pl.conf
  addons/GME/Language/GME_localization.pt_br.conf
  addons/GME/Language/GME_localization.ru_ru.conf
  addons/GME/Language/GME_localization.st
  addons/GME/Language/GME_localization.uk_ua.conf
  addons/GME/Language/GME_localization.zh_cn.conf
Labels: translation
